#!/bin/zsh

export NVM_DIR="$HOME/.nvm"

unfunction nvm

[ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && \
  source "$(brew --prefix)/opt/nvm/nvm.sh"

# This loads nvm bash_completion
[ -s "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm" ] && \
  source "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm"

\nvm "$@"
