# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

format = """
$time\
$cmd_duration\
$username\
$hostname\
$directory\
$git_status\
$git_state\
$git_branch\
$line_break\
$character"""

[time]
disabled = true
format = "[  $time]($style)"
style = "bright-yellow"

[cmd_duration]
disabled = true
format = "[󰔛 $duration]($style)"
style = "dimmed yellow"
show_milliseconds = true
min_time = 0

[directory]
format = "[$read_only]($read_only_style)[ ](bold bright-cyan)[$path]($style) "
style = "bold cyan"
read_only = " "
read_only_style = "bold yellow"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "italic bright-gray"
symbol = ""
# symbol = " "

[git_status]
format = '[ ](red)[$all_status$ahead_behind]($style)'
style = ""
conflicted = "[ ](red)"
untracked = "[ ](bright-green)"
modified = "[ ](yellow)"
staged = "[ ](green)"
renamed = "[ ](purple)"
deleted = "[ ](red)"
stashed = "[ ](gray)"
ahead = "[ ](green)"
behind = "[ ](red)"
diverged = "[繁](red)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[ruby]
format = "[$symbol($version)]($style) "
symbol = " "

[nodejs]
format = "[$symbol($version)]($style) "
symbol = " "

[character]
# success_symbol = "[❯  ](purple)"
success_symbol = "[ ](green)"
error_symbol = "[ ](red)"

